apiVersion: apps/v1
kind: Deployment
metadata:
  name: legal-assistant-backend
  labels:
    app: legal-assistant
    component: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: legal-assistant
      component: backend
  template:
    metadata:
      labels:
        app: legal-assistant
        component: backend
    spec:
      containers:
      - name: backend
        image: legal-assistant-genai:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: legal-assistant-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: legal-assistant-secrets
              key: redis-url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: legal-assistant-secrets
              key: secret-key
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: legal-assistant-secrets
              key: openai-api-key
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: legal-assistant-secrets
              key: anthropic-api-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: upload-storage
          mountPath: /app/data/uploads
        - name: processed-storage
          mountPath: /app/data/processed
      volumes:
      - name: upload-storage
        persistentVolumeClaim:
          claimName: legal-assistant-uploads-pvc
      - name: processed-storage
        persistentVolumeClaim:
          claimName: legal-assistant-processed-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: legal-assistant-backend-service
spec:
  selector:
    app: legal-assistant
    component: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: legal-assistant-frontend
  labels:
    app: legal-assistant
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: legal-assistant
      component: frontend
  template:
    metadata:
      labels:
        app: legal-assistant
        component: frontend
    spec:
      containers:
      - name: frontend
        image: legal-assistant-frontend:latest
        ports:
        - containerPort: 8501
        env:
        - name: BACKEND_URL
          value: "http://legal-assistant-backend-service"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: legal-assistant-frontend-service
spec:
  selector:
    app: legal-assistant
    component: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8501
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: legal-assistant-uploads-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: legal-assistant-processed-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: legal-assistant-secrets
type: Opaque
data:
  database-url: cG9zdGdyZXNxbDovL3VzZXI6cGFzc0BkYi9sZWdhbF9hc3Npc3RhbnQ=
  redis-url: cmVkaXM6Ly9yZWRpcy1zZXJ2aWNlOjYzNzk=
  secret-key: eW91ci1zdXBlci1zZWNyZXQta2V5LWNoYW5nZS1pbi1wcm9kdWN0aW9u
  openai-api-key: eW91ci1vcGVuYWktYXBpLWtleQ==
  anthropic-api-key: eW91ci1hbnRocm9waWMtYXBpLWtleQ==